# Generated by Django 4.1 on 2022-09-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0002_alter_popularity_content_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prevention',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='followup',
            name='action',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prevention',
            name='action',
        ),
        migrations.RemoveField(
            model_name='prevention',
            name='date',
        ),
        migrations.RemoveField(
            model_name='prevention',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='prevention',
            name='user',
        ),
    ]
