# Generated by Django 4.1.1 on 2022-09-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0006_alter_reply_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='quotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_reply', to='managing.reply'),
        ),
    ]
